### ISSUE TITLE
Error: /app/validator/image.binary: not found

### ISSUE THREAD

**Issue by joncursi** [eth2-educators/medalla-exit#2]
Hi there!

I am seeing the following error when running the `validator-voluntary-exit` command:

```
➜  medalla-exit git:(main) sudo docker-compose run validator-voluntary-exit
Creating medalla-exit_validator-voluntary-exit_run ... done
/setup/process-exit.sh: line 4: /app/validator/image.binary: not found
/setup/process-exit.sh: line 5: /app/validator/image.binary: not found
```

This is happening for me on:

* macOS 11.0.1 (Big Sur)
  * Docker Desktop version 2.5.0.1 (49550)
  * Docker version 19.03.13 (build 4484c46d9d)
  * Docker Compose version 1.27.4 (build 40524192)
* Also on a fresh installation of Ubuntu 20.04 LTS

Thoughts?

**Comment by yorickdowne** [comment]
This was caused by the project pulling "latest-debug", which has the binary in a different location. I've updated it to pull a beta.2 image. It'll run now; it won't send the exit because the cloud beacon has been shut down.
Thank you for the report!
